name: Auto Update Cluster_CDN.DL-Global.list

on:
  schedule:
    - cron: '0 4 * * *'  # 北京时间每天12点运行
  workflow_dispatch:  # 手动触发工作流

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # 选择Python版本

      - name: Install Required Libraries
        run: |
          python -m pip install requests

      - name: Run Python Script to Generate New File
        run: |
          python Ruleset/Updater/Cluster_CDN.DL-Global/Cluster_CDN.DL-Global.py

      - name: Configure Git with virtual identity
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Automated Bot"
     
      - name: Commit and Push Changes
        run: |
          git add Ruleset/Cluster_CDN.DL-Global.list
          git commit -m "Automated update of Cluster_CDN.DL-Global.list"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
